
import tkinter as tk 
from tkinter import *
from tkinter import ttk
window = tk.Tk()
window.title("T-Town clinic database")
dogphoto = PhotoImage(file="dog.png")
label1 = tk.Label(window, image=dogphoto)
button1 = tk.Button(window,text="search by name")
entry1 = tk.Entry(window,text="Entry widgets can be typed in", width=13)
label2 = tk.Label(window,text="search by name")
num3 = tk.Label(window,text="\n\nclient database")
nu1 = tk.Label(window,text="name")
nu2 = tk.Label(window,text="type")
nu3 = tk.Label(window,text="breed")
nu4 = tk.Label(window,text="owner")
nu5 = tk.Label(window,text="birthdate")
eny1 = tk.Entry(window,text="rf", width=10)
eny2 = tk.Entry(window,text="wf", width=10)
eny3 = tk.Entry(window,text="asd", width=10)
eny4 = tk.Entry(window,text="adsf", width=10)
eny5 = tk.Entry(window,text="hg", width=10)
label1.grid(row = 0, column = 1)
bon1 = tk.Button(window,text="save entry")
bon2 = tk.Button(window,text="<preveus")
bon3 = tk.Button(window,text="next>")
num3.grid(row=0, column = 3,  )
nu1.grid(row=1, column = 1, sticky=W )
nu2.grid(row=1, column = 2, sticky=W )
nu3.grid(row=1, column = 3, sticky=W )
nu4.grid(row=1, column = 4, sticky=W )
nu5.grid(row=1, column = 5, sticky=W )
eny1.grid(row=2, column = 1, sticky=W )
eny2.grid(row=2, column = 2, sticky=W )
eny3.grid(row=2, column = 3, sticky=W )
eny4.grid(row=2, column = 4, sticky=W )
eny5.grid(row=2, column = 5, sticky=W )
button1.grid(row = 0, column = 4, sticky=NE )
entry1.grid(row = 0, column = 5, sticky=NE )
bon1.grid(row = 3, column = 3, sticky=W )
bon2.grid(row = 3, column = 1, sticky=W )
bon3.grid(row = 3, column = 5, sticky=W )
window.mainloop()